name: cogfun
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - numpy=2.2.5
  - scikit-learn=1.6.1
  - matplotlib=3.10.3
  - pandas=2.2.3
  - pytorch=2.3.0
  - networkx=3.3
  - pygame=2.6.1
  - pip=24.0
  - pip:
    - galois==0.4.6
    - ogb==1.3.6
    - umap-learn==0.5.7
    - tqdm==4.67.1
    - torch-geometric==2.5.0
    - pytest==7.4.4